//-- Treant
//models/items/furion/treant/the_ancient_guardian_the_ancient_treants/the_ancient_guardian_the_ancient_treants.vmdl
//models/items/furion/treant/furion_treant_nelum_red/furion_treant_nelum_red.vmdl
//models/items/furion/treant/fungal_lord_shroomthing/fungal_lord_shroomthing.vmdl
//
//-- Bear
//models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl
//models/items/lone_druid/true_form/dark_wood_true_form/dark_wood_true_form.vmdl
