"Shops"
{
    "npc_town_shopkeeper"
    {
        "01"
        {
            "ItemsCosts"
            {
                "item_broadsword_tier1" "129"
                "item_broadsword_tier2" "299"
                "item_broadsword_tier3" "1195"
                "item_kobold_weapon_1" "345"
                "item_kobold_amulet_1" "849"
                "item_3132" "3295"
            }
        }
    }
}
